export const dailyPrompt = [
    "Reflect on the small victory that made you smile today.",
    "What is one thing you're grateful for right now?",
    "Describe a moment today when you felt truly at peace.",
    "What is a personal strength that helped you overcome a challenge recently?",
    "Write about a place that makes you feel safe and comfortable.",
    "What is a dream you have for the future?",
    "Describe a person who has positively influenced your life and why.",
    "What is a simple pleasure that brings you joy?",
    "Reflect on a lesson you learned recently and how it has impacted you.",
    "What are three things you can do to take care of yourself this week?",
    "What is one thing you can let go of to make more space for positivity?",
    "What is a recent challenge you faced and how did you overcome it?",
    "What are you looking forward to in the coming days?",
    "What is one thing you want to achieve by the end of the week?",
    "Describe a moment when you felt truly connected to someone else.",
    "What is a challenge you are currently facing and how can you overcome it?",
    "What is one thing you can do today to make someone else's day better?",
    "Reflect on a time when you felt proud of yourself.",
    "What is one habit you want to develop for a healthier lifestyle?",
    "Describe a moment when you felt inspired and motivated."
]